backend:
  name: github
  repo: tkdrenam/adam.esp.br
  branch: master
  base_url: https://adam.esp.br
  auth_endpoint: api/auth
  commit_messages:
    create: 'feat: create {{collection}} “{{slug}}”'
    update: 'feat: update {{collection}} “{{slug}}”'
    delete: 'feat: delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] upload “{{path}}”'
    deleteMedia: '[skip ci] delete “{{path}}”'

media_folder: 'public/assets'
public_folder: 'assets'

collections:
  - name: 'pages'
    label: 'Páginas'
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'history'
        label: 'História'
        file: 'content/pages/history.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'championships'
        label: 'Títulos'
        file: 'content/pages/championships.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'structure'
        label: 'Estrutura'
        file: 'content/pages/structure.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - name: 'images'
            label: 'Fotos'
            widget: 'list'
            field: { label: 'Foto', name: 'image', widget: 'image' }
      - name: 'board'
        label: 'Diretoria'
        file: 'content/pages/board.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'muaythai'
        label: 'Muaythai'
        file: 'content/pages/muaythai.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'mma'
        label: 'MMA'
        file: 'content/pages/mma.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'jiujitsu'
        label: 'Jiujitsu'
        file: 'content/pages/jiujitsu.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'kickboxing'
        label: 'Kickboxing'
        file: 'content/pages/kickboxing.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'hapkido'
        label: 'Hapkido'
        file: 'content/pages/hapkido.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'taekwondo'
        label: 'Taekwondo'
        file: 'content/pages/taekwondo.md'
        fields:
          - { label: 'Título da página', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - name: 'contact'
        label: 'Contato'
        file: 'content/pages/contact.md'
        fields:
          - { label: 'Endereço', name: 'address', widget: 'string' }
          - { label: 'Telefone', name: 'phone', widget: 'string' }
          - { label: 'E-mail', name: 'email', widget: 'string' }
          - { label: 'Twitter', name: 'twitter', widget: 'string' }
          - { label: 'Facebook', name: 'facebook', widget: 'string' }
          - { label: 'Instagram', name: 'instagram', widget: 'string' }

  - name: 'authors'
    label: 'Autores'
    label_singular: 'Autor'
    create: true
    delete: false
    editor:
      preview: false
    folder: 'content/authors'
    identifier_field: 'name'
    fields:
      - { label: 'Nome', name: 'name', widget: string }
      # - { label: 'Foto', name: 'profile_picture', widget: image, allow_multiple: false }

  - name: 'tags'
    label: 'Tags'
    label_singular: 'Tag'
    create: true
    delete: false
    editor:
      preview: false
    folder: 'content/tags'
    identifier_field: 'name'
    fields:
      - { label: 'Nome', name: 'name', widget: string }

  - name: 'blog'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Título da notícia', name: 'title', widget: 'string' }
      - { label: 'Resumo', name: 'description', widget: 'string' }
      - {
          label: 'Data de publicação',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          dateFormat: 'DD/MM/YYYY',
          timeFormat: false,
        }
      - { label: 'Imagem destaque', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Autor',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          valueField: 'name',
          searchFields: ['name'],
          displayFields: ['name'],
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          multiple: true,
          required: false,
          valueField: 'name',
          searchFields: ['name'],
          displayFields: ['name'],
        }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
